version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
    - 5044:8080
    depends_on:
      - keycloak_web
  keycloak_web:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak_web
    environment:
      #USERNAME: katya
      #PASSWORD: admin
      
      KEYCLOAK_ADMIN: katya
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - 8180:8080
